version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2

  web1:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=redis

  web2:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  redis-data:
